### ISSUE TITLE
Initial load

### ISSUE THREAD

**Issue by karkius** [alexanderar/Mvc.CascadeDropDown#1]
Hello,

Great helper, but there appears to be no possibility to load initial data without using javascript. How can I get the dropdowns to load with lists from the first form load?

**Comment by alexanderar** [comment]
Hello @karkius 
First of all thanks for using the helper, I am very glad that it is useful not only for me.

Now regarding the issue:
It was fixed. I published a new fixed [1.1.0 version to Nuget](https://www.nuget.org/packages/Mvc.CascadeDropDown/1.1.0) and updated the source code. 

All you need to do for is to specify selected values in the model.

For example if you have following view:

```
@using Mvc.CascadeDropDown

@Html.DropDownListFor(m=>m.SelectedCountry, Model.Countries, "Please select a Country", new {@class="form-control"})

@Html.CascadingDropDownListFor(m => m.SelectedCity, m => m.SelectedCountry,  Url.Action("GetCities", "Home"), "country", "Please select a City", true, new { @class = "form-control" })
```

By setting the values for `SelectedCountry` and `SelectedCity` model properies in your controller action:

```
public ActionResult YurAction()
{
     var model = new CascadingDropdownsModel
     {
          Countries =  GetCountriesList(),            
          SelectedCountry = "US",
          SelectedCity = "New York",
      };
      return View(model);
}
```

Cascading drop-down first will load all the cities for 'US' country and it will try to select a 'New York' city from the loaded result.

I hope it helps.

Regards, 
Alex
