### ISSUE TITLE
does not have a parameter named 'actionParam'

### ISSUE THREAD

**Issue by jiecerbo** [alexanderar/Mvc.CascadeDropDown#12]
I'm getting the following error: 

> The best overload for 'CascadingDropDownListFor' does not have a parameter named 'actionParam'

**Comment by alexanderar** [comment]
Could you please post your code

**Comment by alexanderar** [comment]
OK, I found the issue. You probably were looking at the example on the README.md. Use 'ajaxActionParamName' instead. I modified README.md to match updated signature

**Comment by alexanderar** [comment]
Feel free to give this library a star if you find it useful.

**Comment by jiecerbo** [comment]
Yes. that solved the issue. Thanks a lot!
