### ISSUE TITLE
Required Field Validation

### ISSUE THREAD

**Issue by yahya1979** [alexanderar/Mvc.CascadeDropDown#14]
I tried to apply required field validation through Data annotation but I failed. Any Idea?

**Comment by alexanderar** [comment]
Validation works absolutely the same as with regular DropDown helpers.
I assume that you are talking about client side validation. If so, you need check that:

1. jquery.validate.js and jquery.validate.unobtrusive.js scripts are included in the view

2. in Web.config: 

  ```
<appSettings>
    <add key="ClientValidationEnabled" value="true" />
    <add key="UnobtrusiveJavaScriptEnabled" value="true" />
  </appSettings>
```
