### ISSUE TITLE
Action sample

### ISSUE THREAD

**Issue by arimaze** [alexanderar/Mvc.CascadeDropDown#18]
Hi,

Could you please provide sample of the action method

I tried something like this, but the dropdown  list has (in my case of 2 integer) 2 blanks item.

```
 public ActionResult GetProcesses(int organization)
        {
            db.Configuration.ProxyCreationEnabled = false;
            //IList<PROCESSES> test = new List<PROCESSES>();
            //test = db.ORGS_PROCESSES.Where(o=>o.ID_ORGANIZATION_ASSIGNMENT.Equals(organization)).Select(s=>s.PROCESSES).ToList();
            //ViewData["processes"] = test;
            //  return Json(test, JsonRequestBehavior.AllowGet); 
            // return View();
            IList<int> iList = new List<int>();
            iList.Add(1);
            iList.Add(2);
           
            return Json(iList, JsonRequestBehavior.AllowGet);

        }
```

thanks and best regards,

**Comment by alexanderar** [comment]
Instead of returning a IList<int> you need to return `List<SelectListItem>` or a `SelectList`

    public ActionResult GetProcesses(int organization)
    {
        IList<SelectListItem> iList = new List<SelectListItem>();
        iList.Add(new SelectListItem {Text = "1" Value= "1"});
        iList.Add(new SelectListItem {Text = "2" Value= "2"});           
        return Json(iList, JsonRequestBehavior.AllowGet);
    }

**Comment by arimaze** [comment]
Oh thank you !
