### ISSUE TITLE
Determine when the data is loaded

### ISSUE THREAD

**Issue by wolfgangjt** [alexanderar/Mvc.CascadeDropDown#19]
I am working on a project that is utilizing this and I have an issue that I am trying to work on/optimize. The idea is that you can select a location (hierarchy is floor/room/cube) that utilizes the cascade or be able to select a user and auto populate the cascade. My issue is that initially the data isn't loaded and when I try to set the values, obviously we run into errors. So I started to use a delay of setting the drop downs that rely on the previous. It... works but obviously is not very well optimized, for example if the program is slow, the delay might not be enough. Is there a way of determining the exact point in which the data is loaded?

**Comment by alexanderar** [comment]
Currently there is no clean way to determine that, but I am working on version 2 of the helper that will allow to specify callbacks for major parts of the flow (BeforeSend/onGetDataSuccess/OnGetDataError). Hopefully it will be released during this month.

**Comment by wolfgangjt** [comment]
Awesome. That would help incredibly immensely!
