### ISSUE TITLE
Question: is it possible to pass 2 parameters 

### ISSUE THREAD

**Issue by tonyzoc** [alexanderar/Mvc.CascadeDropDown#20]
is it possible to pass 2 parameters like:
 ajaxActionParamName:="YEAR,PERIOD"?

**Comment by alexanderar** [comment]
In current version it is not possible to pass 2 dynamic parameters. I am working on v2 implementation that is supposed to allow this use case

**Comment by alexanderar** [comment]
V2 has been released. So now it is possible to pass multiple parameters by modifying the request in beforeSendData callback. 

You can read about it here:
https://github.com/alexanderar/Mvc.CascadeDropDown/wiki/CascadingDropDown-with-multiple-dependencies-(V2-only)

I also updated the test project with this scenario: https://github.com/alexanderar/Mvc.CascadeDropDown/blob/master/Mvc.CascadeDropDown.Test/Views/Home/MultipleDependencies.cshtml
