### ISSUE TITLE
Force the change trigger through jquery

### ISSUE THREAD

**Issue by wolfgangjt** [alexanderar/Mvc.CascadeDropDown#21]
Is it possible to force the change trigger on a parent element? For example, say I have a parent and a child dropdown. I select an item from the parent and the child loads the data and then I select a child. Once I click a button to add them to a table, I sometimes have trouble "resetting" the elements. If I set the value of the parent to the "" element, the data from the child still exists. I have tried using:

`$("#elementID").val("")`

as well as 

```
var test = document.getElementById("elementID");
var testoption = $("#elementID option");
var testVal = testoption.filter(function() {return $(this).html() === "Default Select Text"}).val();
test.value = testval;
```

Sometimes I can get it to properly reset and sometimes the child data is still loaded until I manually change the parent's selected item.

**Comment by alexanderar** [comment]
In version 1.3.2 you can trigger change on parent element by manually creating change event and dispatching it:
```
 var evt = document.createEvent("HTMLEvents");
 evt.initEvent("change", false, true);
 $("#elementID")[0].dispatchEvent(evt);
```

In version 2 (which is currently being tested and planned to be release by the end of this month) you could do it by triggering change event through jQuery:

 `$("#elementID").trigger("change");`

**Comment by wolfgangjt** [comment]
Wow that helps so much. I appreciate the help!

**Comment by alexanderar** [comment]
V2 has been released so you should be able to use 
`$("#elementID").trigger("change");`
