### ISSUE TITLE
Question: Preset selections upon page load

### ISSUE THREAD

**Issue by wolfgangjt** [alexanderar/Mvc.CascadeDropDown#23]
I have tried a few different ways to try and get my dropdown lists to load with an option already selected but fail every time. Do I set up a new cascadingdropdown model and set the selected options there in the controller before I send to the view or is there another way?

I am using Distinct for my dropdowns because of the way our DB is set up to get the locations, trying to set a value while using Distinct usually just auto-selects the first option because it cannot find the option I specified even though it is clearly there, just filtered (I know, the index is shifted in distinct from my preset value).

**Comment by alexanderar** [comment]
The correct way to preset the value is to set it in the model before rendering the view. You can see the example in the test project: https://github.com/alexanderar/Mvc.CascadeDropDown/blob/master/Mvc.CascadeDropDown.Test/Controllers/HomeController.cs#L57

**Comment by wolfgangjt** [comment]
Gah, I figured out my issue. I was using a model within a my main view model to handle my CDDL, but moving it up a level made it work. Thanks a bunch!
