### ISSUE TITLE
Problems with model inside model

### ISSUE THREAD

**Issue by NunoRebocho** [alexanderar/Mvc.CascadeDropDown#26]
Hi,

I have a model that bind fields on Razor. My model have another model with fields to dropdown.

Example:
class Class1() { Classe 2 };
class Classe2() { country, city, street}

In razor the dropdown Id is 'classe2_country' but the identifier to triggered is document.getElementById('county').

How I resolve this problem?

Thanks

Nuno Rebocho

**Comment by alexanderar** [comment]
You are absolutely right. This was a bug.
I fixed it and released a new version of a library: https://www.nuget.org/packages/Mvc.CascadeDropDown/2.0.1.

Give it a try and let me know if the issues is resolved.
(Don't forget to give us a star :-) )

**Comment by NunoRebocho** [comment]
Hi Alex,

The new release works perfectly!!

Thanks

2017-08-15 12:39 GMT+01:00 Alex Artyomov <notifications@github.com>:

**Comment by alexanderar** [comment]
Great!
