### ISSUE TITLE
Multiple Dropdowns dependent on same "Master"

### ISSUE THREAD

**Issue by Anders205** [alexanderar/Mvc.CascadeDropDown#28]
Hello,
Exellent control, but I have one issue.
I am trying to create a page with multiple DropDowns.
I create the page with three controls. A, B and C. A is independent. B is dependent on A, and C is dependent on A and B. Everything works as expected.

I now add dropdown D and make it dependent on A. D works, but B (and therefore C) is not working anymore.

Is there a way to make this work?

Anders

**Comment by alexanderar** [comment]
Released in [v2.0.3](https://www.nuget.org/packages/Mvc.CascadeDropDown/2.0.3)
