### ISSUE TITLE
Ampersand breaking cascades

### ISSUE THREAD

**Issue by wolfgangjt** [alexanderar/Mvc.CascadeDropDown#30]
When the selected value has an ampersand in the text, it breaks the value retrieve for the child.

For example, I select 'PH&T', the value the controller action receives is just 'PH', thus none of the child options populate.

Any suggestions?

**Comment by alexanderar** [comment]
@wolfgangjt,
I fixed the issue and released a [new 2.0.2 version](https://www.nuget.org/packages/Mvc.CascadeDropDown/2.0.2).

I am waiting for your feedback on this issue to close ticket.

**Comment by wolfgangjt** [comment]
Yeah, works 100%, thanks! I actually made the same changes later that day and completely forgot to check this. You rock!
