### ISSUE TITLE
Problem with validation

### ISSUE THREAD

**Issue by juaniot** [alexanderar/Mvc.CascadeDropDown#34]
Hi, I have a problem with jquery validation. I am using the option "disabledWhenParentNotSelected" with some drop down list; the last one is required for my model but the rest no. The problem is that I select an option in the first ddl, the second is enabled but the rest no so if a click on submit button, the form is send because my last ddl is disabled and validation can't read it. I have been testing and I have been observed that if ddl have attributte "readonly" instead "disabled" this field is validated. ¿There is any way to change disabled by readonly when I set disabledWhenParentNotSelected: true or something similar?

Thanks a lot.

**Comment by alexanderar** [comment]
Unfortunately there is no way to change disabled by readonly but you can set  disabledWhenParentNotSelected to false and then add readonly to all the dropdowns manually.
You can also add custom validation logic to your form.
