### ISSUE TITLE
Selected item posting "null"

### ISSUE THREAD

**Issue by JagHond37** [alexanderar/Mvc.CascadeDropDown#7]
Hi,
I've successfully implemented the cascading drop down menus and they work fine, except when I post the form the value of the selected item in the second drop down list (in your example it would be SelectedCity) is always "null", my guess is that this value is being set to null at some point earlier on and not getting updated to the selected value once a change is made.

**Comment by alexanderar** [comment]
You are describing very basic scenario that should work without any issues. You can see this scenario working in the test project.
In order to help you, I need to see your code.(Model, View and Controller post action).

**Comment by JagHond37** [comment]
Yes it is a very basic use case, I tried to debug it myself but realized that the object created in the post method for the selected value of VehicleModel had a variable that appeared to be manually set to null:

Model:

```
namespace CC2015.Models
{
    public class DealerStock
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        [Column(TypeName = "varchar")]
        [Display(Name = "Make")]
        public string VehicleMake { get; set; }

        [Required]
        [StringLength(50)]
        [Column(TypeName = "varchar")]
        [Display(Name = "Model")]
        public string VehicleModel { get; set; }
```

Controller:

```
public ActionResult GetVehicleModels(string vehicleMake)
        {
            var modelLists = new List<string>();

            var modelQuery = from d in db.VehicleModels
                             where d.VehicleMakeLabel == vehicleMake
                            select d.vehicleModelLabel;

            modelLists.AddRange(modelQuery.Distinct());
            var vehicleModels = new SelectList(modelLists);

            return Json(vehicleModels, JsonRequestBehavior.AllowGet);
        }

// POST: DealerStock/Create
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult DealerStockCreate(DealerStock dealerInput, FormCollection form)
        {
            var userId = User.Identity.GetUserId().ToString();
            var userLoggedIn = db.Users.First(x => x.Id == userId);
            var dealerCode = userLoggedIn.DealerCode.ToString();
            var userNameID = userLoggedIn.UserName.ToString();

            try
            {
                //Load non cascading drop down lists:
                LoadDropDownLists();

                using (db)
                {

                    var makeListItem = db.VehicleMakes.ToList().Select(x => new SelectListItem
                    {
                        Value = x.vehicleMakeLabel,
                        Text = x.vehicleMakeLabel
                    });

                    SelectList makeList = new SelectList(makeListItem, "Value", "Text", "1");

                    ViewBag.vehicleMake1 = makeList;
                    if (ModelState.IsValid)
                    {
                        dealerInput.DateAdded = DateTime.Now.ToString();
                        dealerInput.ApplicationUserDealerCode = dealerCode;
                        dealerInput.SoldStatus = "In stock";

                        db.DealerStocks.Add(dealerInput);
                        db.SaveChanges();
                        return RedirectToAction("DealerStockCreate");
                    }
                }
                return RedirectToAction("SearchMyInventory");
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes (Post). Try again, and if the problem persists see your system administrator.");

            }
            return View("DealerStockCreate");
        }

```

View:

```
@using (Html.BeginForm("DealerStockCreate", "DealerStock", FormMethod.Post))
{
     @Html.AntiForgeryToken()
    <div class="form-horizontal container-fluid col-xs-offset-1">
        @*<h4>Dealer Stock Input</h4> onchange = "this.form.submit();*@
        <h2>Create new stock item</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.VehicleMake, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-3">
                    @Html.DropDownListFor(model => model.VehicleMake, (SelectList)ViewBag.vehicleMake1, "Please select a make", new { @class = "form-control"})
                    @Html.ValidationMessageFor(model => model.VehicleMake, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.VehicleModel, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-3">
                    @Html.CascadingDropDownListFor(model => model.VehicleModel, triggeredByProperty: model => model.VehicleMake, url: Url.Action("GetVehicleModels", "DealerStock"), ajaxActionParamName: "vehicleMake", optionLabel: "Please select a model", disabledWhenParrentNotSelected: true, htmlAttributes: new { @class = "form-control"})
                    @Html.ValidationMessageFor(model => model.VehicleModel, "", new { @class = "text-danger" })
                </div>
```

Debug:
![image](https://cloud.githubusercontent.com/assets/19381655/15282336/298c3092-1b75-11e6-90da-dde607c99f1d.png)

**Comment by alexanderar** [comment]
`GetVehicleModels`generates invalid select list for `VehicleModel`. I see that in the post action it comes with the string value "null" and not as `null` (look at the debug screenshot and compare to `VehiclePower` for example). 

Instead of this:

`var vehicleModels = new SelectList(modelLists);`

try this:

 `var vehicleModels = modelLists.Select(s => new SelectListItem{Text = s, Value = s});`

**Comment by JagHond37** [comment]
Ha thanks, that worked a treat. So if the generated model list was invalid, why did I get the correct list of vehicle models displaying in the view?

**Comment by alexanderar** [comment]
Correct select html element should look like this:

```
<select name="VehicleModel">
     <option value="118d">118d</option>
</select>
```

What you see on the screen is not the `value`property but the text of an option tag, but when you post the form the `value` is posted

Both `DropDownListFor`and `CascadingDropDownListFor`use `SelectList`(or a `IEnumerable<SelectListItem>`) to generate the options for select element
In your case `new SelectList(modelLists);` wasn't setting the `Value`property of `SelectListItem`correctly so `CascadingDropDownListFor`generated options like this:

`<option value="null">118d</option>`

I am glad that now everything works as expected.

P.S. Feel free to give CascadingDropDown a star in github ;-)

**Comment by viktoralfa19** [comment]
Hola tuve el mismo error, mencionado, solo que si me venia un valor de null no "null", pero al parecer todo es porque esta utilizando un @Html.EditorFor(), cuando entraba ahi el valor del combo es null, pero lo coloque de manera directa en la vista donde estaba el @Html.EditorFor() y si me envía el valor del combo. Hice esto porque el objeto que entraba al editorfor era una lista pero ya lo cambie para que sea una entidad. Algo adicional cuando existe este tipo de objetos complejos como listas dentro de otro objeto, el nombre de los controles se colocan en función de la estructura para llegar a la propiedad, entonces no se si el error era por ahi. por ejemplo en el editor el objeto que entraba era esto @Html.EditorFor(m => m.authUserModelDto.Profile, "AuthUserModelDto"), entonces el nombre del combo si no defino la propiedad ID, es authUserModelDto_Profile_Id_Unidad. Por eso es que tal vez me preguntaba si el valor nulo era por esos nombres que se forman de esta manera, ahora cuando indicas un valor de ID, ahi en cambio el TargetElement o TriggerElement no tienen los mismos nombres y genera un error en la carga en cascada.
Esper les sirva esta información y puedan despejar mi duda, Gracias.
